// Generated by Wrangler on Sun Jul 07 2024 09:07:14 GMT+0100 (West Africa Standard Time)
// by running `wrangler types`

interface Env {
	DB_NAME: "postgres";
	DB_USERNAME: "postgres.dmyldrxpkkrkktmqjrwr";
	DB_HOST: "aws-0-eu-central-1.pooler.supabase.com";
	DB_PORT: 6543;
	DB_PASSWORD: string;
	JWT_SECRET: string;
	JWT_PASSPHRASE: string;
}
